name: ci playground
on: [push]
jobs:
  build:
    name: build job
    runs-on: ubuntu-16.04
    steps:
      - name: test echo
        run: echo hello
      - name: Check out Git repository
        uses: actions/checkout@v2
#      - name: run shell
#        uses: appleboy/scp-action@master
#        with:
##          SECRET: ${{ secrets.SECRET }}
#          username: ${{ secrets.USER }}
#          host: ${{ secrets.HOST }}
#          key_path: ${{ secrets.FILENAME }}
#          key: ${{ secrets.SECRET }}
#          source: "test.ts"
#          target: "/"
      - name: run shell
        env:
          #          SECRET: ${{ secrets.SECRET }}
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
          FILENAME: ${{ secrets.FILENAME }}
          SECRET: ${{ secrets.SECRET }}
        run: |
          chmod 777 ./.github/scripts/deploy.sh
          ./.github/scripts/deploy.sh

