name: ci playground
on: [push]
jobs:
  build:
    name: build job
    runs-on: ubuntu-16.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: add secret_key
        run: echo ${{ secrets.SECRET }} > temp_key
      - name: change mode
        run: chmod 777 temp_key
      - name: deploy
        run: scp test.js -i temp_key ${{ secrets.USER }}@${{ secrets.HOST }}:/
