name: ci playground
on: [push]
jobs:
  build:
    name: build job
    runs-on: ubuntu-16.04
    steps:
      - name: test echo
        run: echo hello
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: add secret_key
        run: echo ${{ secret.SECRET }} > temp_key
      - name: change mode
        run: chmod 777 temp_key
      - name: deploy
        run: scp test.js -i temp_key ${{ secret.USER }}@${{ secret.HOST }}:/
