name: ci playground
on: [push]
jobs:
  build:
    name: build job
    runs-on: ubuntu-16.04
    steps:
      - name: test echo
        run: echo hello
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: run shell
        uses: appleboy/scp-action@master
#        run: |
#          chmod 777 ./.github/scripts/deploy.sh
#          ./.github/scripts/deploy.sh
        with:
#          SECRET: ${{ secrets.SECRET }}
          username: ${{ secrets.USER }}
          host: ${{ secrets.HOST }}
          key_path: ${{ secrets.FILENAME }}
          key: ${{ secrets.SECRET }}
          source: "test.ts"
          target: "/"
#      - name: add secret_key
#        run: echo "${{ secrets.SECRET }}" > temp_key
#      - name: change mode
#        run: chmod 777 temp_key
#      - name: deploy
#        run: scp -i temp_key test.js ${{ secrets.USER }}@${{ secrets.HOST }}:/

